version: "3"
services:
  database:
    restart: always
    image: mysql:5.7
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  web:
    build: .
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    ports:
      - 3001:3001
    depends_on:
      - database
    command: ["./wait-for-it.sh", "database:3306", "--", "npm", "start"] # <-- look here!
